{{- if .Values.deployment.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homelab-chart.fullname" . }}
  labels:
    {{- include "homelab-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "homelab-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "homelab-chart.labels" . | nindent 8 }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "homelab-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- $pvcVolumeMounts := list }}
      {{- if and .Values.pvc.create .Values.pvc.pvcs }}
      {{- range .Values.pvc.pvcs }}
      {{- if .mountPath }}
      {{- $pvcVolumeMounts = append $pvcVolumeMounts (include "homelab-chart.pvcVolumeMount" . | fromYaml) }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
        {{- if .Values.deployment.containers }}
        {{- range .Values.deployment.containers }}
        {{- include "homelab-chart.container" (dict "container" . "root" $ "pvcVolumeMounts" $pvcVolumeMounts) | nindent 8 }}
        {{- end }}
        {{- else }}
        {{- $ports := list }}
        {{- if .Values.service.ports }}
        {{- range .Values.service.ports }}
        {{- $ports = append $ports (dict "name" .name "containerPort" (default .port .targetPort) "protocol" (default "TCP" .protocol)) }}
        {{- end }}
        {{- else }}
        {{- $ports = append $ports (dict "name" (default "http" .Values.service.name) "containerPort" (default (default 80 .Values.service.port) .Values.service.targetPort) "protocol" (default "TCP" .Values.service.protocol)) }}
        {{- end }}
        {{- $container := dict "name" .Chart.Name "image" .Values.deployment.image "securityContext" .Values.deployment.securityContext "ports" $ports "livenessProbe" .Values.deployment.livenessProbe "readinessProbe" .Values.deployment.readinessProbe "resources" .Values.deployment.resources "volumeMounts" .Values.deployment.volumeMounts "env" .Values.deployment.env "envFrom" .Values.deployment.envFrom }}
        {{- include "homelab-chart.container" (dict "container" $container "root" . "pvcVolumeMounts" $pvcVolumeMounts) | nindent 8 }}
        {{- end }}
      {{- $volumes := list }}
      {{- if and .Values.pvc.create .Values.pvc.pvcs }}
      {{- range .Values.pvc.pvcs }}
      {{- if .mountPath }}
      {{- $volumes = append $volumes (include "homelab-chart.pvcVolume" . | fromYaml) }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.deployment.volumes }}
      {{- $volumes = concat $volumes .Values.deployment.volumes }}
      {{- end }}
      {{- if $volumes }}
      volumes:
        {{- toYaml $volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
