{{- range .Values.sealedsecrets -}}
{{- $namspace := $.Release.Namespace -}}
{{- $name := .name -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
  namespace: {{ $namspace }}
spec:
  encryptedData:
    {{- range $key, $value := .data }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    type: Opaque
    metadata:
      name: {{ $name }}
      namespace: {{ $namspace }}
{{- end -}}