{{- if .Values.sealedsecrets -}}
{{- $name := .secretName | default include "homelab-chart.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedsecrets }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    type: Opaque
    metadata:
      name: {{ $name }}
      namespace: {{ .Release.Namespace }}
{{- end -}}