apiVersion: v2
name: homelab-chart
description: Helm chart for generic kubernetes deployments
type: application
version: 0.0.14
appVersion: "1.16.0"
maintainers:
  - name: kdwils
    url: https://github.com/kdwils
